#4. Design automation script which accept directory name and mail id from user and create log
#file in that directory which contains information of running processes as its name, PID,
#Username. After creating log file send that log file to the specified mail.
#Usage : ProcInfoLog.py Demo Marvellousinfosystem@gmail.com
#Demo is name of Directory.
#marvellousinfosystem@gmail.com is the mail id.

import os;
import time;
import datetime;
from sys import *;
import EmailModule;
import ProcessModule as proc;
import ChecksumFunctionalityModule as module;


def CreateOutput(DirName,list):

	if(not os.path.exists(DirName)):
		os.mkdir(DirName);

	
	seperator = "-" * 80;
	#FileName =  os.path.join(DirName,"Marvellous%s.log"%(time.ctime()));
	FileName =  os.path.join(DirName,str("Marvellous %s.log"%(time.ctime())).replace(':','_').replace(' ','_') );
	print(FileName);
	
	
	data = "";
	for element in list:
		data += str(element) + "\n";

	fd = open(FileName,"x");
	fd.write(seperator + "\n");
	fd.write("Marvellous Process Logger : "+time.ctime() + "\n");
	fd.write(seperator + "\n\n");
	fd.write(data);
	fd.close();
	return FileName;

def CreateMail(To,FileName):
	username = "harshalghule20@gmail.com";
	password = "***************";
	to = To;
	
	subject  = """
	Marvellous Process Log generated at : %s
	""" %(time);

	body =  """
	Hello %s 
	Welcome to Automation.
	Please find attached documents which contains log of running process.
	Log file is created at : %s

	This is autogenerated mail.
	Please do not reply.

	Thanks & Regards,
	Harshal Narayan Ghule
	""" %(To[0:To.rfind('@')],time.ctime());

	if EmailModule.is_connected():
		EmailModule.sendmail(username,password,To,FileName,subject,body);


def main():
	if  len(argv) != 3:
		print("Invalid number arguments");
		exit();

	if (argv[1] == "-h") or (argv[1] == "-H"):
		print("\n\n\t\t........................This is Process Automation........................\n\n");
		print("\n " + argv[0]+ " -h For Help");
		print("\n " + argv[0]+ " -u For Usage");		
		exit();

	if (argv[1] == "-u") or (argv[1] == "-U"):
		print("\n <Usage> " + argv[0] + "Directory name" + "Senders Email address");
		exit();

	try:
		DirName = argv[1];
		To = argv[2];
		List = proc.GetAllProcess();
		filename = CreateOutput(DirName,List);
		CreateMail(To,filename);

	except Exception as E:
		fd = open("Error_Log.txt",'a');
		logmsg = "\n\n Error :  "+ str(E) + "\n Log Time " + str(datetime.datetime.now()) +"\n\n";
		fd.write(logmsg);
		fd.close();

if(__name__ == "__main__"):
	main();